--SUBCONSULTAS
--SON CONSULTAS QUE NECESIAN DEL RESULTADO DE OTRA CONSULTA PARA PODER SER EJECUTADAS 
--NO SON AUTONOMAS , NECESITAN DE ALGUN VALOR
--NO IMPORTA EL NIVEL DE ANINDAMIENTO DE SUBCONSULTAS, AUNQUE PUEDEN RENTALIZAR LA RESPUESTA
--GENERA BLOQUEOS EN CONSULTAS SELECT, LO QUE TAMBIEN RELENTIZA LAS RESPUESTA
--DEBEMOS INTENTAR DE EVITARLAS EN LA MEDIDA DE LO POSIBLE CON SELECT SIEMPRE QUE SE TENGA RELACION ENTRE TABLAS.

--QUIERO VISUALIZAR LOS DATOS DEL EMPLEADO QUE MAS COBRA DE LA EMPRESA (EMP)
SELECT MAX(SALARIO) FROM EMP;
--650000
select * from emp where salario=(select max(salario) from emp);
--MOSTRAR TODOS LOS EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE EL EMPLEADO GIL Y QUE COBREN ME NOS QUE JIMENEZ
SELECT * 
FROM EMP 
WHERE OFICIO= (SELECT OFICIO FROM EMP WHERE APELLIDO ='gil')
and SALARIO <(SELECT SALARIO FROM EMP WHERE APELLIDO ='jimenez');

--MOSTRAR TODOS LOS EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE EL EMPLEADO GIL Y EL MISMO OFICIO QUE JIMENEZ

--si una consulta devuelve mas de un valor, se utiliza el operador IN

SELECT * 
FROM EMP 
WHERE OFICIO in (SELECT OFICIO FROM EMP WHERE APELLIDO ='gil' OR APELLIDO='jimenez');

--MOSTRAR EL APELLIDO Y EL OFICIO DE LOS EMPLEADOS DEL DEPARTAMENTO MADRID

select apellido, oficio from emp where dept_no=
(selec dept_no from dept where loc='Madrid');

--LO MEJOR SERIA

select e.apellido, d.loc
from emp e
inner join dept d
on e.dept_no = d.dept_no
where d.loc ='MADRID';

--CONSULTAS DE UNION

--MUESTRAN EN UN MISMO CURSOR, UN MISMO CONJUNTO DE RESULTADOS 
--ESTAS CONSULTAS SE UTILIZAN COMO CONCEPTO, NO COMO RELACION
--DEBEMOS SEGUI TRES NORMAS:
--1) LA PRIMERA CONSULTA ES LA JEFA
--2) TODAS LAS CONSULTAS DEBEN TENER EL MISMO NUMERO DE COLUMNAS
--3) TODAS LAS COLUMNAS DEBEN TENER EL MISMO TIPO DE DATO ENTRE SI
--EN NUESTRA BASE DE DATOS, TENEMOS DATOS DE PERSONAS EN DIFERENTES TABLAS
--EMP, PLANTILLA Y DOCTOR

SELECT APELLIDO, OFICIO, SALARIO FROM EMP
union
select apellido, funcion, salario from plantilla
union
select dnombre,loc, dept_no from dept;

--PODEMOS ORDENAR SIN PROBLEMAS
--EN LAS CONSULTAS UNION DEBERIAMOS UTILIZAR SIEMPRE EL NUMERO DE LA COLUMNA PARA ORDENAR
SELECT APELLIDO, OFICIO, SALARIO AS SUELDO FROM EMP
union
select apellido, funcion, salario from plantilla
union
select dnombre,loc, dept_no from dept
ORDER BY 3;

--SE PUEDE FILTRAR LOS DATOS DE LAS CONSULTAS
--POR EJEMPLO MOSTRAR LOS DATOS DE LAS PERSONAS QUE COBREN MENPS DE 300000
--PARA FILTRAR LAS TRES CONSULTAS DEBE APLICARSE EL WHERE A CADA LINEA DE CONSULTAS Y DEPUES REALIZAR SU UNION
--UNION ELIMINA LOS DATOS REPETIDOS, SI QUEREMOS QUE NO SE ELIMINAN SE DEBE UTILIZAR UNION ALL
SELECT APELLIDO, OFICIO, SALARIO AS SUELDO FROM EMP
WHERE SALARIO < 300000
union ALL
select apellido, funcion, salario from plantilla
WHERE SALARIO < 300000
union ALL
select APELLIDO,ESPECIALIDAD, SALARIO from DOCTOR
WHERE SALARIO < 300000
ORDER BY 3;