--CONSULTAS DE COMBINACION
--NOS PERMITEN MOSTRAR DATOS DE VARIAS TABLAS QUE DEBEN ESTAR RELACINADAS ENTRE SI MEDIANTE ALGUNA CLAVE
--1- NECESITAMOS CAMPO/S RELACION ENTRE LAS TABLAS
--2-DEBEMOS PONER EL NOMBRE DE CADA TABLA Y CADA CAMPO EN LA CONSULTA

-- SINTAXIS:
--SELECT TABLA1.CAMPO1 , TABLA 1.CAMPO2, TABLA2.CAMPO1, TABLA2.CAMPO2
--FROM TABLA1
--INNER JOIN TABLA2
--ON TABLA1.CAMPO_RELACION= TABLA2.CAMPO_RELACION

--EJEMPLO:
--MOSTRAR EL APELLIDO, EL OFICIO DE EMPLEADOS JUNTO A U NOMBRE DE DEPARTAMENTO Y LOCALIDAD

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

--QUEREMOS MOSTRAR LOS DATOS SOLO DE MADRID
SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC
FROM EMP
INNER JOIN DEPT 
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE DEPT.LOC='MADRID';

--NO ES OBLIGATORIO INCLUIR EL NOMBRE DE LA TABLA ANTES DEL CAMPO A MOSTRAR EN EL SELECT
--PODEMOS INCLUIR ALIAS 
SELECT e.APELLIDO, e.OFICIO, d.DNOMBRE, d.LOC
FROM EMP e
INNER JOIN DEPT d 
ON e.DEPT_NO = d.DEPT_NO;

--TENEMOS MULTIPLES TIPOS JOIN EN LAS BASES DE DATOS
--INNER: COMBINA LOS RESULTADOS DE LAS DOS TABLAS
--LEFT: COMBINA LAS DOS TABLAS Y TAMBIEN LA TABLA IZQUIERDA
--RIGHT: COBINA LAS DOS TABLAS Y TAMBIEN LA TABLA DERECHA
--FULL: COMBINA LAS DOS TABLAS Y FUEZA LAS DOS TABLAS
--CROSS: ES EL PRODUCTO CARTESIANO, COMBINA CADA DATO DE UNA TABLA CON LOS OTROS DATOS DE LA TABLA


SELECT DISTINCT DEPT_NO FROM EMP;
SELECT *FROM DEPT;

--TENEMOS UN DEPARTAMENTO:40, PRODUCCION, GRANADA SIN EMPLEADOS
--VAMOS A CREAR UN NUEVO EMPLEADO QUE NO TENGA DEPARTAMIENTO



INSERT INTO Emp VALUES('14050', 'SIN DEPT', 'EMPLEADO',7907, TO_DATE('23-07-1967', 'DD-MM-YYYY') 162510,0,50);
--INNER: COMBINA LOS RESULTADOS DE LAS DOS TABLAS
SELECT e.apellido, d.dnombre, d.loc
from emp e
inner join dept d
on e.dept_no = d.dept_no;

--LEFT: COMBINA LAS DOS TABLAS Y TAMBIEN LA TABLA IZQUIERDA
SELECT e.apellido, d.dnombre, d.loc
from emp e
left join dept d
on e.dept_no = d.dept_no;

--RIGHT: COBINA LAS DOS TABLAS Y TAMBIEN LA TABLA DERECHA
SELECT e.apellido, d.dnombre, d.loc
from emp e
right join dept d
on e.dept_no = d.dept_no;

--full: COBINA LAS DOS TABLAS Y TAMBIEN LOS DATOS QUE NO COINCIDAN
SELECT e.apellido, d.dnombre, d.loc
from emp e
full join dept d
on e.dept_no = d.dept_no;

--CROSS: PRODUCTO CARTESIANO
SELECT e.apellido, d.dnombre, d.loc
from emp e
CROSS join dept d;

--MOSTRASR LAS MEDIA SALARIAL DE LOS DOCTORES POR HOSPITAL, MOSTRANDO EL NOMBRE DEL HOSPITAL
SELECT AVG (SALARIO) AS PROMEDIO, HOSPITAL_COD
FROM DOCTOR
GROUP BY HOSPITAL_COD;

SELECT AVG(d.SALARIO) AS PROMEDIO, h.NOMBRE
FROM DOCTOR d
INNER JOIN HOSPITAL h
ON d.hospital_cod = h.hospital_cod
GROUP BY h.NOMBRE;

select count(*) as empleados, dept.loc
from emp
right join dept 
on emp.dept_no = dept.dept_no
group by dept.loc;
