--TAMAÑO DE LETRA
--COMENTARIOS
/*
MAS DE UNA LINEA DE COMENTARIO
TENDREMOS TODAS NUESTRAS CONSULTAS
*/
--NO DIFERENCIA MAYUSCULAS DE MINUSCULAS EN LA PALABRA CLAVE
SELECT * FROM EMP;
SELECT * FROM dept;